POST http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYW1pbnVmYXRpbWFAZ21haWwuY29tIiwiaWF0IjoxNzY5MzI0Mjk0LCJleHAiOjE3NjkzMjc4OTQsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.vqjgnN33AMD0j1wxX6e6912PDB2VMW23eVJUQYBZRAA

{
    "username": "Fatee",
    "fullname": "Fatima Aminu",
    "email": "aminufatima@gmail.com",
    "password": "FatimaAminu@123"
}

GET http://localhost:3000/users

 
POST http://localhost:3000/auth/signIn
Content-Type: application/json
{
    "email": "aminufatima@gmail.com",
    "password": "FatimaAminu@123"
}

### Submit puzzle answer (earns XP)
POST http://localhost:3000/progress/submit
Content-Type: application/json

{
  "userId": "1",
  "puzzleId": "dcebf04a-542f-464d-92e4-3ad983cde9ba",
  "answer": "42"
}

POST http://localhost:3000/auth/signIn
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYW1pbnVmYXRpbWFAZ21haWwuY29tIiwiaWF0IjoxNzY5MzI0Mjk0LCJleHAiOjE3NjkzMjc4OTQsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.vqjgnN33AMD0j1wxX6e6912PDB2VMW23eVJUQYBZRAA
{
    "email": "bibikudibrahim@gmail.com",
    "password": "Password@123"
}

# forgot password
POST http://localhost:3000/auth/forgot-password
Content-Type: application/json
{
    "email": "aminubabafatima8@gmail.com"
}

// reset passwors
POST http://localhost:3000/auth/reset-password/:token
Content-Type: application/json
{
    "password": "FatimaAminu@123"
}


GET http://localhost:3000/puzzles/daily-quest 

### Get all puzzles
GET http://localhost:3000/puzzles

### Get puzzles by category
GET http://localhost:3000/puzzles?categoryId=397b1a88-3a41-4c14-afee-20f57554368b

### Get puzzles by difficulty
GET http://localhost:3000/puzzles?difficulty=INTERMEDIATE

### Get puzzles by category AND difficulty
GET http://localhost:3000/puzzles?categoryId=397b1a88-3a41-4c14-afee-20f57554368b&difficulty=INTERMEDIATE

### Get puzzles with pagination
GET http://localhost:3000/puzzles?page=1&limit=10

### Get puzzles with all filters
GET http://localhost:3000/puzzles?categoryId=397b1a88-3a41-4c14-afee-20f57554368b&difficulty=INTERMEDIATE&page=1&limit=10


GET http://localhost:3000/users/1/xp-level


GET http://localhost:3000/users?limit=10&page=1


# create a puzzle (category ID here is not in the database. You will have to seed it to get one)
POST http://localhost:3000/puzzles

{
  "question": "What has keys but cannot open locks?",
  "options": ["A piano", "A map", "A keyboard", "A code"],
  "correctAnswer": "A piano",
  "difficulty": "INTERMEDIATE",
  "categoryId": "4f506168-29bc-4b42-b198-dd9f4667d442",
  "timeLimit": 60,
  "explanation": "A piano has keys but cannot open locks."
}

POST http://localhost:3000/categories
Content-Type: application/json

{
  "name": "Business",
  "description": "Business transactions",
  "isActive": true
}

// get category endpoints
GET http://localhost:3000/categories

# Sample account to test and navigate around the app
Username: phertyameen
email: phertymahmohd@gmail.com
password: phertyAmeen@1


POST http://localhost:3000/auth/forgot-password
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYW1pbnVmYXRpbWFAZ21haWwuY29tIiwiaWF0IjoxNzY5MzI0Mjk0LCJleHAiOjE3NjkzMjc4OTQsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.vqjgnN33AMD0j1wxX6e6912PDB2VMW23eVJUQYBZRAA
{
    "email": "bibikudibrahim@gmail.com"
}

POST http://localhost:3000/auth/reset-password/TOKEN_FROM_LOG
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYW1pbnVmYXRpbWFAZ21haWwuY29tIiwiaWF0IjoxNzY5MzI0Mjk0LCJleHAiOjE3NjkzMjc4OTQsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.vqjgnN33AMD0j1wxX6e6912PDB2VMW23eVJUQYBZRAA
{
    "email": "bibikudibrahim@gmail.com"
}